### PR TITLE
AoT compilation support fixes

### PR DESCRIPTION
**Pull request by xaralis**
In order to use this library with AoT compiler, I had to change few bits to be public. Otherwise, compiler complains when building ngfactories. E.g.:

```
ERROR in ./aot/~/ng2-sidebar/lib/sidebar.component.ngfactory.ts
Module build failed: Error: /Users/xaralis/Workspace/d21-web-president-client/aot/node_modules/ng2-sidebar/lib/sidebar.component.ngfactory.ts (309,41): Property '_visibleSidebarState' is private and only accessible within class 'Sidebar'.)
```

Once few properties are made public, everyting works as it should.

### CODE REVIEW

**Comment by arkon** [comment]
@xaralis I didn't realize private fields didn't work for AOT, so thanks! Can I request that the "private" stuff are still prefixed with underscores to at least imply that they're meant to be private though?

**Comment by arkon** [comment]
Actually, I've published v1.6.2 with a slightly different change. Let me know if that works.

**Comment by arkon** [comment]
I'm assuming it's fine now, so I'll close this...

**Comment by xaralis** [comment]
@arkon Sorry, didn't have time to try it again but I will soon.

**Pull request closed without merging**
